### ISSUE TITLE
Can not run in win32

### ISSUE THREAD

**Issue by Prondtoo** [n0mjs710/DMRlink#16]
"for sig in [signal.SIGTERM, signal.SIGINT, signal.SIGQUIT]:"

On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. A ValueError will be raised in any other case.

https://docs.python.org/2/library/signal.html

**Comment by n0mjs710** [comment]
Maybe it wasn't intended to run on Win32?
